### ISSUE TITLE
Rune pouch

### ISSUE THREAD

**Issue by mcgeer** [mcgeer/WastedBankSpace#11]
If there is a check for rune pouch not being full, it would be useful to add a check to fill it with runes. ONLY flag runes if this condition is true as to not put flags on all runes.

**Comment by JonStudders** [comment]
I dont believe this would be a useful addition.
With pouch only holding 16k rune and most players happy to use placeholders for runes.

**Comment by mcgeer** [comment]
Agreed, also more complicated with the 4 pouch now
