### ISSUE TITLE
Add Costume Room

### ISSUE THREAD

**Issue by Nick2bad4u** [mcgeer/WastedBankSpace#22]
Here is a list of bank tags for all items that can be stored in PoH costume room.

`items_storable_in_the_costume_room,24442,7400,6110,6111,6106,6107,6108,6109,6151,6153,10418,10414,10416,10410,10412,6141,10406,6143,10408,6145,10402,10404,10400,6147,6149,6130,6131,6133,6135,6137,6139,6128,6129,10458,10454,10456,10460,10462,6182,6184,6185,6186,6187,6188,10446,10448,10442,10444,6180,6181,10450,10452,10436,10438,10432,10434,10440,10428,10424,10426,10420,10422,10430,2633,2631,2639,2637,2635,2621,2629,2627,2625,2623,2609,2611,2619,23789,2617,2615,23785,2613,23787,10468,10464,10466,10472,10474,10470,2607,2605,2603,2601,2675,2673,2671,2665,2663,2661,2669,2667,2655,2653,2651,22498,2659,2657,22496,22494,2643,2641,2649,2647,2645,9949,9944,9948,9945,9946,9921,9922,9920,9925,9923,9924,7321,7323,7325,7327,7319,9950,7362,7364,7366,11862,11863,7368,7350,11858,7352,7354,11854,11856,11850,11852,11860,22500,7356,7358,22502,7340,7342,11847,7344,7346,7348,10507,7332,7334,7336,7338,6070,7392,7394,6065,7396,6067,7399,6068,7398,11899,11898,11895,11894,11897,11896,7390,21214,6069,21211,7382,7384,7386,7388,10552,10553,7380,10555,21209,11893,7370,7372,10549,7374,7376,10547,10548,10550,10551,23859,7378,21298,21295,21287,2591,2599,2597,2595,2593,2581,2589,2587,2585,2583,2577,2579,8970,8971,8961,8960,8963,8962,8965,8964,8967,8966,8969,8968,8959,8952,8954,8953,8956,8955,8958,8957,6351,6353,6355,6357,6359,8992,6330,8991,8994,8993,8996,8995,6335,8997,6337,6339,6322,6324,6326,6328,1506,12845,22244,22242,22234,24880,12896,12895,24878,24874,24876,24872,12889,12888,12887,12892,12891,12894,12893,12890,10288,10296,10298,10292,10294,10290,10284,10286,10280,10282,8840,8842,8839,12959,12958,12957,12956,7593,7592,7595,7594,7596,10336,10338,10332,11664,11663,10334,11665,10340,10342,24977,22316,24975,10322,10324,10330,10318,10314,10316,10310,10312,10320,10308,10304,10306,10300,10302,10376,10378,10384,10386,10380,10382,21024,22353,21021,22351,10366,10368,10372,10374,10370,1419,21018,10358,10354,10356,10362,10364,10360,10348,10344,10346,10350,10352,22328,22327,22326,21073,21076,21070,22394,21061,22392,21067,22396,21064,22390,22388,10398,10388,10394,10396,10390,10392,25037,25031,25034,25028,25025,25022,25019,25013,25016,25010,25007,25004,25001,25075,25078,25072,25069,13072,13073,13070,13069,13068,22838,6570,25084,25081,6568,20220,20211,20217,20214,548,546,20208,20202,20205,10864,10865,10862,10863,22842,22840,22846,22844,20260,20263,20257,20254,20251,20246,20243,20249,20240,20235,20232,20229,20223,20226,20272,20266,20269,26445,26442,7927,26436,26439,26433,26430,26427,25157,25155,25135,25137,25131,25133,26460,25129,26454,26451,26448,10939,10933,25174,25176,25171,25173,25167,25169,25163,25165,13182,10941,10940,21695,13203,26517,13218,13216,13217,13215,13223,13221,13222,6722,11901,11900,4117,4115,4113,4111,4107,4105,4103,4101,4109,11919,11990,21301,21304,11964,11966,22684,20020,20014,22675,20017,20011,20008,20005,20000,21314,20059,20056,20050,20053,20047,20044,20041,22698,20035,20038,22695,20032,22692,20026,20023,21354,20029,22689,9068,9069,20095,20092,20098,20089,20083,20086,20080,9099,9097,9098,9096,9070,9073,9074,9071,9072,6633,6627,6629,6623,6625,6617,6619,6665,6666,6654,6655,6656,26256,26258,26254,22717,22715,22719,22713,22701,4091,4099,4097,4095,4093,4089,4072,4071,4070,4079,4069,4068,20140,20134,20137,20131,20125,20122,20128,20119,20113,20116,20110,21439,20101,20107,20104,20181,20187,20184,20178,20172,20175,20169,20166,20161,20164,20158,20155,20152,20146,20149,20199,20193,20196,20190,24189,24184,24185,24180,24182,24183,4339,4331,4333,4335,4337,24177,24178,24179,24173,24174,24175,24176,24170,24171,24172,12199,4329,12195,12197,4321,12193,4323,4325,4327,24166,24167,24168,24169,24162,24163,24164,24165,24160,24161,4317,4319,4310,24159,4315,24155,24157,24158,24151,24153,4306,4308,4300,4302,24149,4304,4371,4373,4375,4377,4379,4361,4363,4365,4367,4369,4351,4353,4355,4357,4359,24195,24197,4341,24198,24191,24192,24194,24190,4343,4345,4347,4349,4391,4393,4395,3061,3060,4397,4399,4381,4383,4385,3059,3058,3057,4387,4389,19691,19693,19695,19697,19699,19687,19689,12201,25502,25500,25553,24223,25555,24224,25551,12239,12235,12237,12243,12245,12241,25549,24215,24211,24213,12229,12225,12227,12231,12233,24207,24209,24203,24204,24206,24200,24201,12217,12219,12213,12215,12221,12223,12207,12209,12203,12205,12211,25596,25598,25592,25594,12279,12287,12289,12283,12285,12281,4411,4413,24250,12269,13599,4405,12275,4407,12277,4409,12271,12273,4401,24248,4403,24249,24244,24240,12257,12259,13589,13597,12265,13595,12267,13593,12261,13591,12263,24236,12247,13579,12249,12253,13587,12255,13585,13583,12251,13581,25557,24294,6860,24291,6862,6861,6863,6866,6865,6867,24288,6859,6858,6857,6856,12297,12299,12293,12295,12291,5574,5575,5576,20720,20712,20710,19724,20704,20708,20706,5553,5554,5555,5556,5557,20779,4298,20773,20777,20775,9100,13609,9104,13607,9102,13605,13603,13601,24300,24301,12317,12319,13647,13645,13646,12315,13643,13644,12321,12309,12305,12307,13637,12301,13635,12303,13633,13641,13642,12311,13640,13629,13627,13625,13623,13621,13631,25604,25606,13619,13617,13615,13613,13611,24342,24344,24340,12357,12359,12363,6916,12365,6918,12361,24338,11019,12349,13679,12345,12347,13677,11022,12353,11021,12355,13681,11020,12351,24325,24327,24321,24323,12339,13669,12335,13667,13665,12337,13675,12341,12343,13673,13671,24317,24319,24313,24315,24311,12327,12329,12323,13655,12325,12331,13663,13664,12333,24307,24309,24302,24303,24304,24305,23056,24387,24389,23053,23050,23047,12389,12397,12399,12393,12395,12391,12379,12385,12387,12381,12383,12367,12369,12375,6924,12377,12371,12373,24346,6920,24348,6922,13287,13288,13285,13286,13283,13284,13281,13280,4565,4566,13258,13259,13261,13260,21720,21719,21793,21791,19476,795,20442,20445,20439,20433,20436,20499,20497,20491,20495,20493,20487,20485,20489,20483,20481,20477,20475,20479,20471,20465,21795,20469,20467,13319,13317,13318,13368,13369,13377,13378,13375,13376,13373,13374,13371,13372,13370,25344,25346,13359,13357,13358,13366,13367,13364,13365,13362,13363,13360,13361,25336,25338,25332,25334,25330,12016,12015,25326,25328,25322,25324,13344,12014,12013,13343,25314,25316,24046,24043,24040,24034,24037,13379,13389,13387,13385,13380,13381,20539,20537,21859,21857,21851,20520,21855,21853,21849,20517,21847,20515,21846,21841,21845,20513,21844,21843,20511,21842,20507,20505,20509,20503,20501,20541,20595,20590,25434,24147,4510,4511,4512,25440,4504,4505,4506,4507,4508,4509,25436,25438,4503,3483,3481,3480,3488,3486,3485,3472,3479,3478,3477,3476,3475,3474,3473,12639,12638,12637,9672,9676,9674,12600,9678,23330,23332,24664,23318,23312,23315,23309,23306,23303,23300,23375,23372,10057,10059,10065,10067,10061,10063,23369,23363,23366,23360,10047,10049,10053,10055,10051,23357,23354,24680,23351,10039,10035,10037,10043,10045,10041,23345,24676,24678,23342,23339,23334,24666,23336,24668,23398,23392,23395,23389,23381,23384,10069,10071,23378,3393,3391,3389,3387,3385,23410,23404,23407,23401,23448,22114,23446,24758,24755,24752,24746,24749,24743,23413,23099,23095,23097,23091,23093,1069,1052,24397,24399,24393,24395,24391,1037,23059,20846,9811,20840,9812,9810,20844,9813,20842,9814,9808,20836,9809,9806,20834,9807,20838,9800,9801,9804,20832,9805,9802,9803,24420,24421,12437,12439,12434,12441,12443,24419,24411,12426,12428,12422,12424,12430,12432,24409,24405,24407,24401,24403,12419,12416,12415,12418,12417,12412,12421,12420,12478,12484,12486,12480,12482,23122,12466,12468,12474,12476,12470,12472,12459,12455,12458,12457,2413,12462,2412,12464,12460,23108,2414,24430,24431,23101,12449,12445,12447,12451,12453,24428,19912,12488,12496,12498,12492,12494,12490,19952,19955,19946,19949,19941,19943,19936,23194,23197,23191,19930,19933,19924,19927,23188,23185,19921,19915,19918,19991,19994,19997,19982,19985,19988,19979,19970,19973,19976,19961,19964,19967,19958,9749,9747,9748,9781,9782,9780,9785,9786,9783,9784,9789,9787,9788,9770,9771,9774,9775,9772,9773,9778,9779,9776,9777,9760,9763,9764,9761,9762,9767,9768,9765,9766,9769,9752,9753,9750,9751,9756,9757,9754,9755,9758,9759,12518,12514,12516,12510,12512,12520,12508,12504,12506,12500,12502,9792,9793,9790,9791,9796,9797,9794,9795,9798,9799,23212,23206,24537,24539,23209,24533,23203,24535,23200,24531,24527,24525,24520,12540,25840,12522,12524,23255,23252,12598,23246,23249,23242,12596,23224,23221,23218,23215,23297,23294,23291,23288,23282,23285,23279,23276,23273,23270,23264,23267,23261,11282,11280,23258`

**Comment by mcgeer** [comment]
Other Issues handle this
