### ISSUE TITLE
Feature Request: Add Hallowed Sepulchre Storage

### ISSUE THREAD

**Issue by H0rseRenoir** [mcgeer/WastedBankSpace#40]
Mysterious Stranger (Hallowed Sepulchre) can store the relevant rewards from here

https://oldschool.runescape.wiki/w/Mysterious_Stranger_(Hallowed_Sepulchre)#Hallowed_Sepulchre_Equipment_Storage

**Comment by JonStudders** [comment]
PR raised: https://github.com/mcgeer/WastedBankSpace/pull/45
