### ISSUE TITLE
Add Victor's Capes variants to storage list

### ISSUE THREAD

**Issue by swirle13** [mcgeer/WastedBankSpace#61]
[Victor's Capes](https://oldschool.runescape.wiki/w/Victor%27s_cape_(1)) are not included in the list when they are storable in the cape rack.

![image](https://github.com/mcgeer/WastedBankSpace/assets/9778474/baf29788-463e-4321-a46e-9846f25c0a31)

**Comment by BramManuel** [comment]
Is this still a problem with the latest update? i have added it to the code:
[    VICTORS_CAPE_1(ItemID.VICTORS_CAPE_1, StorageLocation.CAPE_RACK),](https://github.com/mcgeer/WastedBankSpace/blob/4df271fa4951c268b018d9a8a99b18844dc458bb/src/main/java/com/wastedbankspace/model/StorableItem.java#L2048)
