### ISSUE TITLE
All items flagged as wasted space regardless of settings

### ISSUE THREAD

**Issue by darkscion0** [mcgeer/WastedBankSpace#81]
Recently something changed and now all items that could be wasted space have the indicator next to them, regardless of what is ticked in the plugin configuration. 

![image](https://github.com/user-attachments/assets/7fd6cc36-9d8f-4e1d-bdca-1fb345b9c788)
![image](https://github.com/user-attachments/assets/0b1a2879-8a15-4071-89f0-e31456065352)

**Comment by mcgeer** [comment]
Ill investigate this weekend

**Comment by darkscion0** [comment]
> Ill investigate this weekend

Thanks. It MAY have broke after installing the Bank Memory plugin but I can't be sure. Uninstalling Bank Memory didn't fix it. Let me know if you need anything else from me. Happy to help.

**Comment by mcgeer** [comment]
Once the plugin hub merge is accepted https://github.com/runelite/plugin-hub/pull/6571 you can reload Runelite and make sure on your end it is working. For now I am closing the Issue as It should be fixed in that change. Thanks for reporting it!

**Comment by darkscion0** [comment]
That fixed it. Works great now. Thank you!
